blueprint:
  name: Zigbee2Mqtt Aqara Magic Cube Control
  description: 'Control Home Assistant automations using Zigbee2mqtt and the Aqara Magic Cube. The possible actions include shake, throw, wakeup, fall, tap, slide, flip180, flip90, rotate_left, and rotate_right.'
  domain: automation
  input:
    cube_entity:
      name: Magic Cube Entity
      description: 'Select the Aqara Magic Cube entity.'
      selector:
        entity:
          domain: sensor
    action_shake:
      name: Shake
      description: 'Action to be executed when the cube is shaken.'
      selector:
        action:
    action_throw:
      name: Throw
      description: 'Action to be executed when the cube is thrown.'
      selector:
        action:
    action_wakeup:
      name: Wakeup
      description: 'Action to be executed when the cube is woken up.'
      selector:
        action:
    action_fall:
      name: Fall
      description: 'Action to be executed when the cube falls.'
      selector:
        action:
    action_tap:
      name: Tap
      description: 'Action to be executed when tapping on the cube.'
      selector:
        action:
    action_slide:
      name: Slide
      description: 'Action to be executed when sliding the cube.'
      selector:
        action:
    action_flip180:
      name: Flip180
      description: 'Action to be executed when the cube is flipped 180 degrees.'
      selector:
        action:
    action_flip90:
      name: Flip90
      description: 'Action to be executed when the cube is flipped 90 degrees.'
      selector:
        action:
    action_rotate_left:
      name: RotateLeft
      description: 'Action to be executed when the cube is rotated counterclockwise.'
      selector:
        action:
    action_rotate_right:
      name: RotateRight
      description: 'Action to be executed when the cube is rotated clockwise.'
      selector:
        action:

trigger:
  - platform: state
    entity_id: !input cube_entity
  - platform: mqtt
    topic: '{{ state_attr(cube_entity, "your_mqtt_topic_attribute") }}'
    payload: shake
    id: shake
  - platform: mqtt
    topic: '{{ state_attr(cube_entity, "your_mqtt_topic_attribute") }}'
    payload: throw
    id: throw
  - platform: mqtt
    topic: '{{ state_attr(cube_entity, "your_mqtt_topic_attribute") }}'
    payload: wakeup
    id: wakeup
  - platform: mqtt
    topic: '{{ state_attr(cube_entity, "your_mqtt_topic_attribute") }}'
    payload: fall
    id: fall
  - platform: mqtt
    topic: '{{ state_attr(cube_entity, "your_mqtt_topic_attribute") }}'
    payload: tap
    id: tap
  - platform: mqtt
    topic: '{{ state_attr(cube_entity, "your_mqtt_topic_attribute") }}'
    payload: slide
    id: slide
  - platform: mqtt
    topic: '{{ state_attr(cube_entity, "your_mqtt_topic_attribute") }}'
    payload: flip180
    id: flip180
  - platform: mqtt
    topic: '{{ state_
