blueprint:
  name: Zigbee2Mqtt Aqara Magic Cube Control (MFKZQ01LM)
  description: 'Control Home Assistant automations using Zigbee2mqtt and the Aqara Magic Cube. The possible actions include shake, throw, wakeup, fall, tap, slide, flip180, flip90, rotate_left, and rotate_right.'
  domain: automation
  input:
    cube_action:
      name: Magic Cube MQTT topic
      description: 'Enter the MQTT topic for the Magic Cube (e.g., zigbee2mqtt/Magic Cube/action).'
      selector:
        text:
    action_shake:
      name: Shake (optional)
      description: 'Action to be executed when the cube is shaken.'
      selector:
        action:
      default: []
    action_throw:
      name: Throw (optional)
      description: 'Action to be executed when the cube is thrown.'
      selector:
        action:
      default: []
    action_wakeup:
      name: Wakeup (optional)
      description: 'Action to be executed when the cube is woken up.'
      selector:
        action:
      default: []
    action_fall:
      name: Fall (optional)
      description: 'Action to be executed when the cube falls.'
      selector:
        action:
      default: []
    action_tap:
      name: Tap (optional)
      description: 'Action to be executed when tapping on the cube.'
      selector:
        action:
      default: []
    action_slide:
      name: Slide (optional)
      description: 'Action to be executed when sliding the cube.'
      selector:
        action:
      default: []
    action_flip180:
      name: Flip180 (optional)
      description: 'Action to be executed when the cube is flipped 180 degrees.'
      selector:
        action:
      default: []
    action_flip90:
      name: Flip90 (optional)
      description: 'Action to be executed when the cube is flipped 90 degrees.'
      selector:
        action:
      default: []
    action_rotate_left:
      name: RotateLeft (optional)
      description: 'Action to be executed when the cube is rotated counterclockwise.'
      selector:
        action:
      default: []
    action_rotate_right:
      name: RotateRight (optional)
      description: 'Action to be executed when the cube is rotated clockwise.'
      selector:
        action:
      default: []

trigger:
  - platform: mqtt
    topic: !input cube_action
    payload: shake
    id: shake
  - platform: mqtt
    topic: !input cube_action
    payload: throw
    id: throw
  - platform: mqtt
    topic: !input cube_action
    payload: wakeup
    id: wakeup
  - platform: mqtt
    topic: !input cube_action
    payload: fall
    id: fall
  - platform: mqtt
    topic: !input cube_action
    payload: tap
    id: tap
  - platform: mqtt
    topic: !input cube_action
    payload: slide
    id: slide
  - platform: mqtt
    topic: !input cube_action
    payload: flip180
    id: flip180
  - platform: mqtt
    topic: !input cube_action
    payload: flip90
    id: flip90
  - platform: mqtt
    topic: !input cube_action
    payload: rotate_left
    id: rotate_left
  - platform: mqtt
    topic: !input cube_action
    payload: rotate_right
    id: rotate_right

action:
  - choose:
      - conditions:
          - condition: trigger
            id: shake
        sequence:
          !input action_shake
      - conditions:
          - condition: trigger
            id: throw
        sequence:
          !input action_throw
      - conditions:
          - condition: trigger
            id: wakeup
        sequence:
          !input action_wakeup
      - conditions:
          - condition: trigger
            id: fall
        sequence:
          !input action_fall
      - conditions:
          - condition: trigger
            id: tap
        sequence:
          !input action_tap
      - conditions:
          - condition: trigger
            id: slide
        sequence:
          !input action_slide
      - conditions:
          - condition: trigger
            id: flip180
        sequence:
          !input action_flip180
      - conditions:
          - condition: trigger
            id: flip90
        sequence:
          !input action_flip90
      - conditions:
          - condition: trigger
            id: rotate_left
        sequence:
          !input action_rotate_left
      - conditions:
          - condition: trigger
            id: rotate_right
        sequence:
          !input action_rotate_right
    default: []
mode: single
