blueprint:
  name: Zigbee2Mqtt Aqara Magic Cube Control
  description: 'Steuerung von Home Assistant-Automatisierungen mit Zigbee2mqtt und dem Aqara Magic Cube. Mögliche Aktionen: shake, throw, wakeup, fall, tap, slide, flip180, flip90, rotate_left und rotate_right.'
  domain: automation
  input:
    cube_action:
      name: Magic Cube MQTT topic
      description: 'Geben Sie das MQTT-Thema für den Magic Cube ein (z. B. zigbee2mqtt/Magic Cube/action).'
      selector:
        text:
    action_shake:
      name: shake
      description: 'Aktion, die ausgeführt wird, wenn der Würfel geschüttelt wird.'
      selector:
        action:
    action_throw:
      name: throw
      description: 'Aktion, die ausgeführt wird, wenn der Würfel geworfen wird.'
      selector:
        action:
    action_wakeup:
      name: wakeup
      description: 'Aktion, die ausgeführt wird, wenn der Würfel aufgeweckt wird.'
      selector:
        action:
    action_fall:
      name: fall
      description: 'Aktion, die ausgeführt wird, wenn der Würfel fällt.'
      selector:
        action:
    action_tap:
      name: tap
      description: 'Aktion, die ausgeführt wird, wenn auf den Würfel getippt wird.'
      selector:
        action:
    action_slide:
      name: slide
      description: 'Aktion, die ausgeführt wird, wenn der Würfel geschoben wird.'
      selector:
        action:
    action_flip180:
      name: flip180
      description: 'Aktion, die ausgeführt wird, wenn der Würfel um 180 Grad gedreht wird.'
      selector:
        action:
    action_flip90:
      name: flip90
      description: 'Aktion, die ausgeführt wird, wenn der Würfel um 90 Grad gedreht wird.'
      selector:
        action:
    action_rotate_left:
      name: rotateLeft
      description: 'Aktion, die ausgeführt wird, wenn der Würfel gegen den Uhrzeigersinn gedreht wird.'
      selector:
        action:
    action_rotate_right:
      name: rotateRight
      description: 'Aktion, die ausgeführt wird, wenn der Würfel im Uhrzeigersinn gedreht wird.'
      selector:
        action:

trigger:
  - platform: mqtt
    topic: !input cube_action
    payload: shake
    id: shake
  - platform: mqtt
    topic: !input cube_action
    payload: throw
    id: throw
  - platform: mqtt
    topic: !input cube_action
    payload: wakeup
    id: wakeup
  - platform: mqtt
    topic: !input cube_action
    payload: fall
    id: fall
  - platform: mqtt
    topic: !input cube_action
    payload: tap
    id: tap
  - platform: mqtt
    topic: !input cube_action
    payload: slide
    id: slide
  - platform: mqtt
    topic: !input cube_action
    payload: flip180
    id: flip180
  - platform: mqtt
    topic: !input cube_action
    payload: flip90
    id: flip90
  - platform: mqtt
    topic: !input cube_action
    payload: rotate_left
    id: rotate_left
  - platform: mqtt
    topic: !input cube_action
    payload: rotate_right
    id: rotate_right

action:
  - choose:
      - conditions:
          - condition: trigger
            id: shake
        sequence:
          !input action_shake
      - conditions:
          - condition: trigger
            id: throw
        sequence:
          !input action_throw
      - conditions:
          - condition: trigger
            id: wakeup
        sequence:
          !input action_wakeup
      - conditions:
          - condition: trigger
            id: fall
        sequence:
          !input action_fall
      - conditions:
          - condition: trigger
            id: tap
        sequence:
          !input action_tap
      - conditions:
          - condition: trigger
            id: slide
        sequence:
          !input action_slide
      - conditions:
          - condition: trigger
            id: flip180
        sequence:
          !input action_flip180
      - conditions:
          - condition: trigger
            id: flip90
        sequence:
          !input action_flip90
      - conditions:
          - condition: trigger
            id: rotate_left
        sequence:
          !input action_rotate_left
      - conditions:
          - condition: trigger
            id: rotate_right
        sequence:
          !input action_rotate_right
    default: []
mode: single
