blueprint:
  name: Zigbee2Mqtt Aqara Magic Cube control
  description: ''
  domain: automation
  input:
    cube_action:
      name: Magic Cube MQTT topic
      description: 'Geben Sie das MQTT-Topic für den Magic Cube ein (z.B. zigbee2mqtt/Magic Cube/action)'
      selector:
        text:
    action_shake:
      name: Shake
      description: Aktion, die bei einer Schüttelbewegung des Cubes ausgeführt wird.
      selector:
        action:
    action_throw:
      name: Throw
      description: Aktion, die bei einem Wurf des Cubes ausgeführt wird.
      selector:
        action:
    action_wakeup:
      name: Wakeup
      description: Aktion, die bei einem Aufwecken des Cubes ausgeführt wird.
      selector:
        action:
    action_fall:
      name: Fall
      description: Aktion, die bei einem Fall des Cubes ausgeführt wird.
      selector:
        action:
    action_tap:
      name: Tap
      description: Aktion, die bei einem Tippen auf den Cube ausgeführt wird.
      selector:
        action:
    action_slide:
      name: Slide
      description: Aktion, die bei einer Verschiebebewegung des Cubes ausgeführt wird.
      selector:
        action:
    action_flip180:
      name: Flip180
      description: Aktion, die bei einer Umklappbewegung des Cubes um 180 Grad ausgeführt wird.
      selector:
        action:
    action_flip90:
      name: Flip90
      description: Aktion, die bei einer Umklappbewegung des Cubes um 90 Grad ausgeführt wird.
      selector:
        action:
    action_rotate_left:
      name: RotateLeft
      description: Aktion, die bei einer gegen den Uhrzeigersinn Drehung des Cubes ausgeführt wird.
      selector:
        action:
    action_rotate_right:
      name: RotateRight
      description: Aktion, die bei einer im Uhrzeigersinn Drehung des Cubes ausgeführt wird.
      selector:
        action:

trigger:
  - platform: mqtt
    topic: !input cube_action
    payload: shake
    id: shake
  - platform: mqtt
    topic: !input cube_action
    payload: throw
    id: throw
  - platform: mqtt
    topic: !input cube_action
    payload: wakeup
    id: wakeup
  - platform: mqtt
    topic: !input cube_action
    payload: fall
    id: fall
  - platform: mqtt
    topic: !input cube_action
    payload: tap
    id: tap
  - platform: mqtt
    topic: !input cube_action
    payload: slide
    id: slide
  - platform: mqtt
    topic: !input cube_action
    payload: flip180
    id: flip180
  - platform: mqtt
    topic: !input cube_action
    payload: flip90
    id: flip90
  - platform: mqtt
    topic: !input cube_action
    payload: rotate_left
    id: rotate_left
  - platform: mqtt
    topic: !input cube_action
    payload: rotate_right
    id: rotate_right

action:
  - choose:
      - conditions:
          - condition: trigger
            id: shake
        sequence:
          !input action_shake
      - conditions:
          - condition: trigger
            id: throw
        sequence:
          !input action_throw
      - conditions:
          - condition: trigger
            id: wakeup
        sequence:
          !input action_wakeup
      - conditions:
          - condition: trigger
            id: fall
        sequence:
          !input action_fall
      - conditions:
          - condition: trigger
            id: tap
        sequence:
          !input action_tap
      - conditions:
          - condition: trigger
            id: slide
        sequence:
          !input action_slide
      - conditions:
          - condition: trigger
            id: flip180
        sequence:
          !input action_flip180
      - conditions:
          - condition: trigger
            id: flip90
        sequence:
          !input action_flip90
      - conditions:
          - condition: trigger
            id: rotate_left
        sequence:
          !input action_rotate_left
      - conditions:
          - condition: trigger
            id: rotate_right
        sequence:
          !input action_rotate_right
    default: []
mode: single
